# Generated by Django 4.1 on 2024-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
