# Generated by Django 4.1 on 2024-05-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_level',
            field=models.IntegerField(default=1),
        ),
    ]
