# Generated by Django 4.1 on 2024-05-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_customuser_bio_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
